version: '3.3'
services:
  app: &app_base
    build:
      context: .
      dockerfile: "Dockerfile"
    command: bin/docker-entrypoint
    volumes:
      - bundle-data:/usr/local/bundle:cached
      - .:/usr/src/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true
  # sidekiq:
  #   <<: *app_base
  #   command: [ "bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml" ]
  #   ports: [ ]
  #   depends_on:
  #     - redis
  #   tty: false
  #   stdin_open: false
  db:
    image: mysql:8.0.32
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
      - ./docker_init/db/init:/docker-entrypoint-initdb.d
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  bundle-data:
  db-data:
  # redis-data:
